### ISSUE TITLE
there is one more issue, i can't right and left clicking at my npc gui

### ISSUE THREAD

**Issue by Asukayuri1402** [samolego/TraderNPCs#6] opened 2022-03-14 03:11 UTC
this is a problem video about the issue
im sorry my English is bad

this is the media fire video, its too big mb so yeah i used media fire link
https://www.mediafire.com/file/qwn2t367f66anbp/Minecraft__1.18.1_-_Singleplayer_2022-03-14_09-51-40.mp4/file

**Comment by samolego** [comment] 2022-03-14 05:38
Can you describe the issue as well?
Also, could you upload the video to a streaming platform (yt, streamable, etc.)?

**Comment by Asukayuri1402** [comment] 2022-03-17 01:50
ok

**Comment by Asukayuri1402** [comment] 2022-03-17 02:01
here
https://www.youtube.com/watch?v=9sVIvuCDhrw

**Comment by samolego** [comment] 2022-03-17 06:30
Using forge?

**Comment by Asukayuri1402** [comment] 2022-03-20 03:10
yes

**Comment by Asukayuri1402** [comment] 2022-03-20 03:11
i using forge

**Comment by samolego** [comment] 2022-03-20 07:04
That's duplicate of #3 . I'm now waiting on https://github.com/architectury/architectury-loom/issues/75 to be resolved.

**Closed by samolego** 2022-03-20 07:04 UTC

**Comment by Asukayuri1402** [comment] 2022-03-22 12:50
so how to repair it?

**Comment by samolego** [comment] 2022-03-22 14:07
Please read the above comment.
